options: remove settings that were removed by rocksdb, get building again
To get building again, we need to make our library current with much
newer versions of rocksdb. Relevant commits in rocksdb to remove
options that our library previously supported:

set_access_hint_on_compaction: 1a885fe73078e6c195cd6d5cd98e6b62c8567a8c
hard/soft rate limit: 1e0e883ca521c05ad63e6fa69c3e50378f3fd34d
set_max_mem: bec9ab4316002257263aef3db254e6ae926eb100
purge_redundant_kvs: 961d8dacf205d225fb75641ab5d98b80900c11ba
rate_limit_delay: 42cca28ebb379177e6248b664eeab8475c3bebcb
skip_log_error: 74ccd1931e226ac10fc9e0c03072098a8304727f
table_cache_remove_scan_count_limit: 92822655fd5571495f720f4d4cc4395e4336e91d
block_cache_compressed: 2800aa069ad49d16c69adbc2a1970d1a990245f9

This patch also used some help from James Bibby's pull request against
DataDog/gorocksdb, which has the same LICENSE file as our license
file.